paginate handled flags
codidact/qpixel pull request #1306
Opened 2024-02-11 20:31 UTC by cellio

I noticed that the (moderator) page of handled flags was getting a little sluggish on our most flag-heavy site.  This one-liner adds pagination.  The pages for pending flags and user flag history were already paginated.  I couldn't find where the list of escalations is produced.  We should check that at some point, but having enough pending escalations to slow down page load also feels like a very rare case.

Proof of pagination (hey, when you need to manufacture 50+ flags to test, the reasons get a little, uh, minimal):

![Screenshot](https://github.com/codidact/qpixel/assets/5557942/96f9983e-843e-4403-84af-3bca4748dff7)

2024-02-12 17:12 UTC, ArtOfCode- requested changes
Is `@flags` paginated in the controller action for this view?

2024-02-12 17:36 UTC, cellio commented
> Is `@flags` paginated in the controller action for this view?

Yes, assuming that https://github.com/codidact/qpixel/blob/e26a930960a1af68c8f7e66bc36a092329027319/app/controllers/flags_controller.rb#L57 is the right place to look.  I see pagination for queue, handled, and escalated there.

2024-02-13 00:08 UTC, ArtOfCode- commented
Huh, wonder why this wasn't done before if it was provided in the controller 🤷🏻

2024-02-13 00:08 UTC, ArtOfCode- approved these changes

2024-02-13 00:08 UTC, merged