automatically focus in the textbox when you start a search
codidact/qpixel pull request #1426
Opened 2024-10-09 20:44 UTC by cellio

Fixes https://github.com/codidact/qpixel/issues/829 by implementing Taeir's suggestion.  (Art approved the approach in the comments there.)

2024-10-11 02:20 UTC, Oaphi submitted a review, later dismissed

2024-10-11 02:20 UTC, Oaphi commented on app/views/layouts/_header.html.erb
> +  function focusSearch() {
A couple of notes:

- avoid using `var` at all costs, `const` for unchangeable cariables and `let` for reassignable is a must:
- the `focusSearch` function has a "scope bleed" - it should be called something like `toggleSearchFocus` and accept a single boolean parameter, which you then pass in the handler function. I'll provide example implementation a bit later

2024-10-12 11:43 UTC, ArtOfCode- requested changes

2024-10-12 11:43 UTC, ArtOfCode- commented on app/views/layouts/_header.html.erb
> +  } else {
style: new line for if-else blocks

```suggestion
  }
  else {
```

2024-10-15 02:45 UTC, trichoplax requested changes
I recommend this pull request be made to Co-Design instead, in the file `js_src/header.ts`, either in the method `toggle`, which starts on [line 32](https://github.com/codidact/co-design/blob/develop/js_src/header.ts#L32), or otherwise in the constructor for the class `HeaderSlideToggle`, which starts on [line 20](https://github.com/codidact/co-design/blob/develop/js_src/header.ts#L20).

The `toggle` method is added as an event listener callback to every slider, so adding the code here when it is only used for the Search slider would be slightly wasteful, but likely imperceptibly so.

Instead modifying the constructor would allow adding the existing `toggle` method to all of the other sliders, and creating a new callback function just for the Search slider, consisting of calling `toggle` and then focusing the text box. This would avoid adding the unneeded code to the other sliders, and would avoid the decision being made each time a slider is opened, instead deciding just once at page load.

2024-10-15 02:56 UTC, trichoplax commented
Straight after recommending making this change in Co-Design instead, I've just seen [Art's comment on the issue this pull request fixes](https://github.com/codidact/qpixel/issues/829#issuecomment-1384651342):

> Probably better to do this in QPixel. Makes more sense for an application-specific use case than doing it as part of the design framework.

This is a good point, and making a special case in the design framework is a little messy. Maybe it's better to keep this in QPixel for now, and avoid changing Co-Design until #1432 is worked on (which is unlikely to be soon as it seems low priority). At that point there would be no special case in Co-Design, as the browser would handle the autofocus automatically with no JS required.

2024-10-15 02:59 UTC, trichoplax approved these changes

2024-10-16 02:30 UTC, ArtOfCode- approved these changes

2024-10-16 02:31 UTC, merged