Better visualization for tag merge (with itself).
codidact/qpixel pull request #176
Opened 2020-09-11 19:00 UTC by galegosimpatico

Flash 400 instead of 500 for the invalid request.

Attempts to tackle issue #175.

2020-09-11 21:40 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      # redirect_to tag_path(id: @category.id, tag_id: @primary.id) && return
This didn't do what I expected, at all.

2020-09-11 21:40 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      # render :edit, status: 400
This worked better than the previous one, but didn't do what anyone would expect it the page to do, TBH I was seeing it coming.

2020-09-11 21:40 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      # render json: { success: false, status: 400, tag: @tag }
This was a very bad idea that seemed not so bad until executed.

2020-09-11 21:40 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      # render 'tag', category: @category, tag: @tag
This wasn't tested very much, I'm no longer even sure it worked at all.

2020-09-11 21:40 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      redirect_back fallback_location: categories_path
This didn't what I was expecting it to do either, at all, but I think the results were unexpectedly great.

2020-09-13 20:54 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +      # redirect_to tag_path(id: @category.id, tag_id: @primary.id) && return
applying technique https://github.com/codidact/qpixel/pull/178/commits/dfae8b9f0a486aca417804fbf14e2d44308841da uses fixes it, but https://github.com/codidact/qpixel/pull/176#discussion_r487302984 is actually better

2020-09-16 09:11 UTC, ArtOfCode- requested changes

2020-09-16 09:11 UTC, ArtOfCode- commented on app/controllers/tags_controller.rb
> +    if params[:merge_with_id].eql? @primary.id.to_s
```ruby
if params[:merge_with_id] == @primary.id.to_s
```

2020-09-16 11:13 UTC, merged

2020-09-16 11:14 UTC, galegosimpatico commented on app/controllers/tags_controller.rb
> +    if params[:merge_with_id].eql? @primary.id.to_s
I tested it and then committed