Stop same post being used in close reasons for itself
codidact/qpixel pull request #416
Opened 2021-01-14 07:16 UTC by sau226

This PR blocks a post from being used to close itself as a duplicate, as well as for any other situation requiring a post as part of the close reason.

Currently, this just displays an HTTP 400 error, with details in JSON. Feel free to improve on the UX here, but it has the desired effect already.

GitHub issue linking tag: Fixes #218

2021-01-14 15:26 UTC, cellio commented
What does the user see when triggering this error?  One of those red banner pop-ups?  With what text?

2021-01-16 00:10 UTC, ArtOfCode- requested changes

2021-01-16 00:10 UTC, ArtOfCode- commented on app/controllers/posts_controller.rb
> +      if other = @post
**error**: you want `other == @post` here - i.e. equality check, rather than assignment

2021-01-16 17:47 UTC, sau226 commented
> What does the user see when triggering this error? One of those red banner pop-ups?

Correct - the user gets a 400 error pop up (maybe with a timestamp) - the actual error is visible in browser console preview and afaik we do something similar for most exceptions like this.

2021-01-16 18:45 UTC, merged