Discard edits when commenting
codidact/qpixel pull request #422
Opened 2021-01-17 15:11 UTC by BoxedFruits

This PR resolves #243 to discard edits when commenting.

2021-01-17 16:24 UTC, ArtOfCode- requested changes

2021-01-17 16:24 UTC, ArtOfCode- commented on app/assets/javascripts/comments.js
> +          <input type="button" name="js-discard-edit" id="js-discard-edit-${commentId}" value="Discard Edit" class="button is-danger is-outlined" />
Can we make this `class="js-discard-edit" data-comment-id="${commentId}"` instead of packing it all into the ID attribute?

2021-01-17 16:24 UTC, ArtOfCode- commented on app/assets/javascripts/comments.js
> +    $(`#js-discard-edit-${commentId}`).click(() => {
This would need updating to use the class attribute as well.

2021-01-18 17:26 UTC, ArtOfCode- requested changes
Should've made myself more clear, sorry. I'd like this to use the class `js-discard-edit`, with _no_ ID on the end of it, and then an _additional_ `data-comment-id` attribute where the comment ID can go. The ckick handler can then either select on all `.js-discard-edit` and deal with all in one handler, or it can select on `.js-discard-edit[data-comment-id="${commentId}"]` if it's easier to handle each one individually.

2021-01-18 19:10 UTC, BoxedFruits commented
> Should've made myself more clear, sorry. I'd like this to use the class `js-discard-edit`, with _no_ ID on the end of it, and then an _additional_ `data-comment-id` attribute where the comment ID can go. The ckick handler can then either select on all `.js-discard-edit` and deal with all in one handler, or it can select on `.js-discard-edit[data-comment-id="${commentId}"]` if it's easier to handle each one individually.

Ohhhh gotcha. I'll update in a bit!

2021-01-20 18:41 UTC, ArtOfCode- approved these changes

2021-01-20 18:42 UTC, merged

2021-01-20 18:42 UTC, ArtOfCode- commented
Thanks! There's a few more [good first issues](https://github.com/codidact/qpixel/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22meta%3A+good+first+issue%22) or [low-complexity tasks](https://github.com/codidact/qpixel/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22complexity%3A+easy%22) if you're looking for more to do.