Voting history (and comment helpers)
codidact/qpixel pull request #617
Opened 2021-08-10 16:36 UTC by luap42

Adds a voting history to user profiles.

Adds comment [helpers].

Work in progress.

2021-08-18 07:44 UTC, luap42 commented
You'd bet this code is foolproof; turns out it isn't :confused: 

```ruby
test "my vote summary redirects to current user summary" do
  sign_in users(:standard_user)
  get :my_vote_summary
  assert_redirected_to vote_summary_path(users(:standard_user).id)
  sign_out :user

  sign_in users(:closer)
  get :my_vote_summary
  assert_redirected_to vote_summary_path(users(:closer).id)
  sign_out :user

  sign_in users(:editor)
  get :my_vote_summary
  assert_redirected_to vote_summary_path(users(:editor).id)
  sign_out :user

  sign_in users(:moderator)
  get :my_vote_summary
  assert_redirected_to vote_summary_path(users(:moderator).id)
  sign_out :user

  sign_in users(:admin)
  get :my_vote_summary
  assert_redirected_to vote_summary_path(users(:admin).id)
  sign_out :user
end
```

2021-08-18 19:14 UTC, ArtOfCode- requested changes

2021-08-18 19:14 UTC, ArtOfCode- commented on app/helpers/comments_helper.rb
> +  def render_comment_helpers(comment_text, user = current_user)
This is going to be a performance killer on a page with any more than a few of these helpers. Currently, this runs at least one query per helper usage. We should cache category lowercase-name/ID/human-name maps heavily - category names and IDs aren't going to change much, ever, so we can afford to basically permanently cache this and add a cache-breaker on category create/update.

2021-08-19 20:26 UTC, ArtOfCode- approved these changes

2021-08-19 20:26 UTC, merged